version: '3'
services:
  app:
    container_name: botzap
    image: edileal1/botwhatsapp:1.7
    restart: unless-stopped
    ports:
      - ${PORT}:3000
    volumes:
      - ./data/.wwebjs_auth:/home/botzap/app/.wwebjs_auth
      - ./data/.wwebjs_cache:/home/botzap/app/.wwebjs_cache
